cmd_scripts/kconfig/qconf.o := g++ -Wp,-MMD,scripts/kconfig/.qconf.o.d -Wall -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -std=c++11 -fPIC -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/arm-linux-gnueabihf/qt5 -c -o scripts/kconfig/qconf.o scripts/kconfig/qconf.cc

source_scripts/kconfig/qconf.o := scripts/kconfig/qconf.cc

deps_scripts/kconfig/qconf.o := \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QAction \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qaction.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtwidgetsglobal.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtguiglobal.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qglobal.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qconfig.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qtcore-config.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsystemdetection.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qprocessordetection.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcompilerdetection.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qtypeinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsysinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qlogging.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qflags.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qatomic.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qbasicatomic.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qatomic_cxx11.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qgenericatomic.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qglobalstatic.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qnumeric.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qversiontagging.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtgui-config.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtwidgets-config.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qkeysequence.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstring.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qchar.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qbytearray.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qrefcount.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qnamespace.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qarraydata.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringliteral.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringalgorithms.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobjectdefs.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobjectdefs_impl.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qwidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qwindowdefs.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobject.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qlist.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qalgorithms.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qiterator.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qhashfunctions.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qpair.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qbytearraylist.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringlist.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qregexp.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringmatcher.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qscopedpointer.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qmetatype.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qvarlengtharray.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcontainerfwd.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobject_impl.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qmargins.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpaintdevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qrect.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsize.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qpoint.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpalette.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qcolor.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qrgb.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qrgba64.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qbrush.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qvector.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qmatrix.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpolygon.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qregion.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qdatastream.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qiodevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qline.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtransform.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpainterpath.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qimage.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpixelformat.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpixmap.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsharedpointer.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qshareddata.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qhash.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsharedpointer_impl.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qfont.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qfontmetrics.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qfontinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qsizepolicy.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qcursor.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qvariant.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qmap.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qicon.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qactiongroup.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qaction.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QApplication \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qapplication.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcoreapplication.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcoreevent.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qeventloop.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qguiapplication.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qinputmethod.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qlocale.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/QCloseEvent \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qevent.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qset.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qurl.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qfile.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qfiledevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qvector2d.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtouchdevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/QDebug \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qdebug.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qtextstream.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcontiguouscache.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QDesktopWidget \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qdesktopwidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QFileDialog \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qfiledialog.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qdir.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qfileinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qdialog.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QLabel \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlabel.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qframe.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QLayout \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlayoutitem.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qboxlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qgridlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/QList \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QMenu \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmenu.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QMenuBar \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmenubar.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmenu.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QMessageBox \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmessagebox.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QToolBar \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtoolbar.h \
  scripts/kconfig/lkc.h \
    $(wildcard include/config/prefix.h) \
  scripts/kconfig/expr.h \
  scripts/kconfig/list.h \
  scripts/kconfig/lkc_proto.h \
  scripts/kconfig/qconf.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QCheckBox \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qcheckbox.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractbutton.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QDialog \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qdialog.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QHeaderView \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qheaderview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractitemview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractscrollarea.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qabstractitemmodel.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qitemselectionmodel.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractitemdelegate.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qstyleoption.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractspinbox.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qvalidator.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qregularexpression.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qslider.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractslider.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qstyle.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtabbar.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtabwidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qrubberband.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QLineEdit \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlineedit.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextcursor.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextformat.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpen.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextoption.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QMainWindow \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmainwindow.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QPushButton \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qpushbutton.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/QSettings \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsettings.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QSplitter \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qsplitter.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QStyledItemDelegate \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qstyleditemdelegate.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QTextBrowser \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtextbrowser.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtextedit.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextdocument.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QTreeWidget \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtreewidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtreeview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtreewidgetitemiterator.h \
  scripts/kconfig/images.h \

scripts/kconfig/qconf.o: $(deps_scripts/kconfig/qconf.o)

$(deps_scripts/kconfig/qconf.o):
